language: java
jdk:
  - oraclejdk7

script: cd MovieFinder && mvn test

branches:
    only:
        - master
        - develop

notifications:
    email: false

cache:
  directories:
    - MovieFinder/src/main/webapp/public/node_modules
    - MovieFinder/src/main/webapp/public/bower_components
